-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  rating INTEGER NOT NULL,
  description TEXT
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating, description)
values
  ('Heroku', 'https://heroku.com', 5, 'This is Heroku description'),
  ('Target', 'https://target.com', 4, 'This is Target description'),
  ('Thinkful', 'https://thinkful.com', 4, 'This is Think outside the classroom'),
  ('Google', 'https://google.com', 5, 'Where we find everything else'),
  ('MDN', 'https://mdn.com', 5, 'The only place to find web documentation'),
  ('Test bookmark', 'https://test.com', 4, 'This is test one'),
  ('Test bookmark2', 'https://test2.com', 4, 'This is test two'),
  ('Test bookmark3', 'https://test3.com', 4, 'This is test three'),
  ('Test bookmark4', 'https://test4.com', 4, 'This is test four'),
  ('Test bookmark5', 'https://test5.com', 4, 'This is test five')
